/*
 * Portal Connect API
 * This is a simple API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.au.eql.cmx.connect.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PremiseData
 */
public class PremiseDataTest {
    private final PremiseData model = new PremiseData();

    /**
     * Model tests for PremiseData
     */
    @Test
    public void testPremiseData() {
        // TODO: test PremiseData
    }

    /**
     * Test the property 'NMI'
     */
    @Test
    public void NMITest() {
        // TODO: test NMI
    }

    /**
     * Test the property 'streetNumber'
     */
    @Test
    public void streetNumberTest() {
        // TODO: test streetNumber
    }

    /**
     * Test the property 'streetName'
     */
    @Test
    public void streetNameTest() {
        // TODO: test streetName
    }

    /**
     * Test the property 'streetType'
     */
    @Test
    public void streetTypeTest() {
        // TODO: test streetType
    }

    /**
     * Test the property 'suburb'
     */
    @Test
    public void suburbTest() {
        // TODO: test suburb
    }

    /**
     * Test the property 'postCode'
     */
    @Test
    public void postCodeTest() {
        // TODO: test postCode
    }

    /**
     * Test the property 'lotNumber'
     */
    @Test
    public void lotNumberTest() {
        // TODO: test lotNumber
    }

    /**
     * Test the property 'planNumber'
     */
    @Test
    public void planNumberTest() {
        // TODO: test planNumber
    }

}
