/*
 * Portal Connect API
 * This is a simple API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.au.eql.cmx.connect.api;

import com.au.eql.cmx.connect.model.Connect;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdminsApi
 */
@Ignore
public class AdminsApiTest {

    private final AdminsApi api = new AdminsApi();

    
    /**
     * create a connect
     *
     * create a connect in peace
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createConnectTest() {
        Connect connect = null;
        api.createConnect(connect);

        // TODO: test validations
    }
    
}
