/*
 * Premise Search API
 * This is a simple API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.au.eql.cmx.premise.api;

import com.au.eql.cmx.premise.model.NMIStatus;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PremiseDetailsApi
 */
@Ignore
public class PremiseDetailsApiTest {

    private final PremiseDetailsApi api = new PremiseDetailsApi();

    
    /**
     * searches premise details
     *
     * By passing in the appropriate options, you can search for available inventory in the system 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPremiseDetailsTest() {
        String nmi = null;
        List<NMIStatus> response = api.getPremiseDetails(nmi);

        // TODO: test validations
    }
    
}
