/*
 * Portal Connect API
 * This is a simple API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.au.eql.cmx.connect.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConnectDetails
 */
public class ConnectDetailsTest {
    private final ConnectDetails model = new ConnectDetails();

    /**
     * Model tests for ConnectDetails
     */
    @Test
    public void testConnectDetails() {
        // TODO: test ConnectDetails
    }

    /**
     * Test the property 'connectType'
     */
    @Test
    public void connectTypeTest() {
        // TODO: test connectType
    }

    /**
     * Test the property 'connectTypeDescription'
     */
    @Test
    public void connectTypeDescriptionTest() {
        // TODO: test connectTypeDescription
    }

    /**
     * Test the property 'contractType'
     */
    @Test
    public void contractTypeTest() {
        // TODO: test contractType
    }

    /**
     * Test the property 'responsibilityCode'
     */
    @Test
    public void responsibilityCodeTest() {
        // TODO: test responsibilityCode
    }

}
