/*
 * Portal Connect API
 * This is a simple API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.au.eql.cmx.connect.model;

import com.au.eql.cmx.connect.model.ConnectDetails;
import com.au.eql.cmx.connect.model.PremiseData;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Connect
 */
public class ConnectTest {
    private final Connect model = new Connect();

    /**
     * Model tests for Connect
     */
    @Test
    public void testConnect() {
        // TODO: test Connect
    }

    /**
     * Test the property 'connectDetails'
     */
    @Test
    public void connectDetailsTest() {
        // TODO: test connectDetails
    }

    /**
     * Test the property 'nmidetails'
     */
    @Test
    public void nmidetailsTest() {
        // TODO: test nmidetails
    }

}
