/*
 * Premise Search API
 * This is a simple API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.au.eql.cmx.premise.model;

import com.au.eql.cmx.premise.model.Address;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for NMIStatus
 */
public class NMIStatusTest {
    private final NMIStatus model = new NMIStatus();

    /**
     * Model tests for NMIStatus
     */
    @Test
    public void testNMIStatus() {
        // TODO: test NMIStatus
    }

    /**
     * Test the property 'nmi'
     */
    @Test
    public void nmiTest() {
        // TODO: test nmi
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'nmiStatus'
     */
    @Test
    public void nmiStatusTest() {
        // TODO: test nmiStatus
    }

    /**
     * Test the property 'connectionType'
     */
    @Test
    public void connectionTypeTest() {
        // TODO: test connectionType
    }

    /**
     * Test the property 'tariff'
     */
    @Test
    public void tariffTest() {
        // TODO: test tariff
    }

}
