/*
 * Portal Connect API
 * This is a simple API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.au.eql.cmx.connect.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConnectDetails
 */
@JsonPropertyOrder({
  ConnectDetails.JSON_PROPERTY_CONNECT_TYPE,
  ConnectDetails.JSON_PROPERTY_CONNECT_TYPE_DESCRIPTION,
  ConnectDetails.JSON_PROPERTY_CONTRACT_TYPE,
  ConnectDetails.JSON_PROPERTY_RESPONSIBILITY_CODE
})
@JsonTypeName("ConnectDetails")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-06T13:38:35.354059+10:00[Australia/Brisbane]")
public class ConnectDetails {
  public static final String JSON_PROPERTY_CONNECT_TYPE = "connectType";
  private UUID connectType;

  public static final String JSON_PROPERTY_CONNECT_TYPE_DESCRIPTION = "connectTypeDescription";
  private String connectTypeDescription;

  public static final String JSON_PROPERTY_CONTRACT_TYPE = "contractType";
  private String contractType;

  public static final String JSON_PROPERTY_RESPONSIBILITY_CODE = "responsibilityCode";
  private OffsetDateTime responsibilityCode;

  public ConnectDetails() { 
  }

  public ConnectDetails connectType(UUID connectType) {
    
    this.connectType = connectType;
    return this;
  }

   /**
   * Get connectType
   * @return connectType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "d290f1ee-6c54-4b01-90e6-d701748f0851", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CONNECT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getConnectType() {
    return connectType;
  }


  @JsonProperty(JSON_PROPERTY_CONNECT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConnectType(UUID connectType) {
    this.connectType = connectType;
  }


  public ConnectDetails connectTypeDescription(String connectTypeDescription) {
    
    this.connectTypeDescription = connectTypeDescription;
    return this;
  }

   /**
   * Get connectTypeDescription
   * @return connectTypeDescription
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Widget Adapter", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CONNECT_TYPE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getConnectTypeDescription() {
    return connectTypeDescription;
  }


  @JsonProperty(JSON_PROPERTY_CONNECT_TYPE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConnectTypeDescription(String connectTypeDescription) {
    this.connectTypeDescription = connectTypeDescription;
  }


  public ConnectDetails contractType(String contractType) {
    
    this.contractType = contractType;
    return this;
  }

   /**
   * Get contractType
   * @return contractType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Widget Adapter", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CONTRACT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getContractType() {
    return contractType;
  }


  @JsonProperty(JSON_PROPERTY_CONTRACT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContractType(String contractType) {
    this.contractType = contractType;
  }


  public ConnectDetails responsibilityCode(OffsetDateTime responsibilityCode) {
    
    this.responsibilityCode = responsibilityCode;
    return this;
  }

   /**
   * Get responsibilityCode
   * @return responsibilityCode
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "2016-08-29T09:12:33.001Z", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_RESPONSIBILITY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getResponsibilityCode() {
    return responsibilityCode;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSIBILITY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponsibilityCode(OffsetDateTime responsibilityCode) {
    this.responsibilityCode = responsibilityCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectDetails connectDetails = (ConnectDetails) o;
    return Objects.equals(this.connectType, connectDetails.connectType) &&
        Objects.equals(this.connectTypeDescription, connectDetails.connectTypeDescription) &&
        Objects.equals(this.contractType, connectDetails.contractType) &&
        Objects.equals(this.responsibilityCode, connectDetails.responsibilityCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(connectType, connectTypeDescription, contractType, responsibilityCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectDetails {\n");
    sb.append("    connectType: ").append(toIndentedString(connectType)).append("\n");
    sb.append("    connectTypeDescription: ").append(toIndentedString(connectTypeDescription)).append("\n");
    sb.append("    contractType: ").append(toIndentedString(contractType)).append("\n");
    sb.append("    responsibilityCode: ").append(toIndentedString(responsibilityCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

