/*
 * Premise Search API
 * This is a simple API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.au.eql.cmx.premise.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Address
 */
@JsonPropertyOrder({
  Address.JSON_PROPERTY_LOT_NO,
  Address.JSON_PROPERTY_STREET,
  Address.JSON_PROPERTY_SUBURB,
  Address.JSON_PROPERTY_POSTCODE,
  Address.JSON_PROPERTY_STATE
})
@JsonTypeName("Address")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-15T17:41:25.017457+10:00[Australia/Brisbane]")
public class Address {
  public static final String JSON_PROPERTY_LOT_NO = "lotNo";
  private String lotNo;

  public static final String JSON_PROPERTY_STREET = "street";
  private String street;

  public static final String JSON_PROPERTY_SUBURB = "suburb";
  private String suburb;

  public static final String JSON_PROPERTY_POSTCODE = "postcode";
  private String postcode;

  public static final String JSON_PROPERTY_STATE = "state";
  private String state;

  public Address() { 
  }

  public Address lotNo(String lotNo) {
    
    this.lotNo = lotNo;
    return this;
  }

   /**
   * Get lotNo
   * @return lotNo
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "30", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LOT_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLotNo() {
    return lotNo;
  }


  @JsonProperty(JSON_PROPERTY_LOT_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLotNo(String lotNo) {
    this.lotNo = lotNo;
  }


  public Address street(String street) {
    
    this.street = street;
    return this;
  }

   /**
   * Get street
   * @return street
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Wedd Street", value = "")
  @JsonProperty(JSON_PROPERTY_STREET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStreet() {
    return street;
  }


  @JsonProperty(JSON_PROPERTY_STREET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStreet(String street) {
    this.street = street;
  }


  public Address suburb(String suburb) {
    
    this.suburb = suburb;
    return this;
  }

   /**
   * Get suburb
   * @return suburb
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Spring Hill", value = "")
  @JsonProperty(JSON_PROPERTY_SUBURB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSuburb() {
    return suburb;
  }


  @JsonProperty(JSON_PROPERTY_SUBURB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuburb(String suburb) {
    this.suburb = suburb;
  }


  public Address postcode(String postcode) {
    
    this.postcode = postcode;
    return this;
  }

   /**
   * Get postcode
   * @return postcode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "4000", value = "")
  @JsonProperty(JSON_PROPERTY_POSTCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPostcode() {
    return postcode;
  }


  @JsonProperty(JSON_PROPERTY_POSTCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPostcode(String postcode) {
    this.postcode = postcode;
  }


  public Address state(String state) {
    
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "QLD", value = "")
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(String state) {
    this.state = state;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Address address = (Address) o;
    return Objects.equals(this.lotNo, address.lotNo) &&
        Objects.equals(this.street, address.street) &&
        Objects.equals(this.suburb, address.suburb) &&
        Objects.equals(this.postcode, address.postcode) &&
        Objects.equals(this.state, address.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lotNo, street, suburb, postcode, state);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Address {\n");
    sb.append("    lotNo: ").append(toIndentedString(lotNo)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    suburb: ").append(toIndentedString(suburb)).append("\n");
    sb.append("    postcode: ").append(toIndentedString(postcode)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

